version: "3"
networks:
  net:
    external: false
services:
  hbbs:
    image: rustdesk/rustdesk-server:1
    command: ["hbbs", "-r", "${PUBLIC_HOST:-rustdesk.example.com}:21117"]
    depends_on:
      - hbbr
    networks:
      - net
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    restart: unless-stopped
    volumes:
      - ./data:/root
  hbbr:
    image: rustdesk/rustdesk-server:1
    command: ["hbbr"]
    networks:
      - net
    ports:
      - 21117:21117
      - 21119:21119
    restart: unless-stopped
    volumes:
      - ./data:/root
